version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data:delegated
  auth-backend:
    tty: true
    container_name: auth-backend
    build: ./spa_auth_app
    command: >
      bash -c 'python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver "0.0.0.0:8000"'
    volumes:
      - ./spa_auth_app:/code:delegated
    #ports:
    #  - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
  auth-frontend:
    tty: true
    container_name: auth-frontend
    build: ./frontend
    command: yarn run serve
    #ports:
    #  - 8080:8080
    expose:
      - 8080
    volumes:
      - ./frontend:/code:delegated
    environment:
      - CHOKIDAR_USEPOLLING=true
  reverse_proxy:
    container_name: server
    build: ./server
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    depends_on:
      - auth-backend
      - auth-frontend

volumes:
  database: